spring:
#  application:
#    name: employment
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/employment?serverTimezone=UTC&characterEncoding=UTF-8
    username: root
    password: yxy
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      maximum-pool-size: 15
      minimum-idle: 5
      idle-timeout: 30000

mybatis:
  type-aliases-package: com.db.employment.dao
  mapper-locations: classpath:mapper/*Mapper.xml
  configuration:
    map-underscore-to-camel-case: true
    use-generated-keys: true
    call-setters-on-nulls: true

server:
  port: 8090


